channels:
  - bokeh
  - conda-forge
dependencies:
  - python
  - matplotlib
  - pandas
  - fastparquet
  - dask
  - distributed
  - bokeh>=2.0.0
  - holoviews 
  - hvplot 
  - geoviews 
  - datashader 
  - colorcet 
  - panel
  - pip
  - pip:
    - jupyter-server-proxy
